# -*- coding: utf-8 -*-
"""Análise da Qualidade do Ar em Capitais Brasileiras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zZsIXd6g7fhthPsvtyyKgOQY4M9QnBcx

# 🌱 Análise da Qualidade do Ar em Capitais Brasileiras

## 1. Introdução

A qualidade do ar é um fator fundamental para a saúde pública e a preservação do meio ambiente. Em grandes cidades, o aumento do tráfego de veículos, da atividade industrial e das queimadas pode elevar a concentração de poluentes como material particulado (PM2.5 e PM10) e ozônio, colocando a população em risco. Este projeto tem como objetivo analisar padrões de poluição atmosférica em algumas capitais brasileiras, identificando tendências temporais e diferenças regionais.

---

## 2. Objetivo

Explorar os dados sobre qualidade do ar em cidades brasileiras para identificar padrões, variações sazonais e possíveis implicações para a saúde pública. O foco é observar os níveis de PM2.5, PM10 e ozônio em São Paulo, Rio de Janeiro e Belo Horizonte.

---

## 3. Fonte de Dados

Os dados utilizados neste projeto foram obtidos a partir de uma base disponível no Kaggle:

📂 Kaggle Dataset: [Air Quality in Brazil](https://www.kaggle.com/datasets/matheusfreitag/air-quality-brazil)

A base foi simplificada e simulada neste projeto para fins didáticos.

---

## 4. Metodologia

- Importação dos dados
- Limpeza e tratamento (datas, colunas, dados faltantes)
- Análise exploratória (gráficos e estatísticas)
- Comparações por cidade e ao longo do tempo

---
"""

# 1. Importação das bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Estilo de gráficos
sns.set(style="whitegrid")

# 2. Simulação dos dados (substituir pelo dataset real se desejar)
data = {
    'cidade': ['São Paulo', 'São Paulo', 'São Paulo',
               'Rio de Janeiro', 'Rio de Janeiro',
               'Belo Horizonte', 'Belo Horizonte'],
    'data': ['2023-01-15', '2023-07-15', '2023-10-15',
             '2023-01-15', '2023-07-15',
             '2023-01-15', '2023-07-15'],
    'pm2_5': [35, 22, 29, 18, 20, 30, 25],
    'pm10': [60, 45, 50, 40, 42, 55, 50],
    'ozonio': [20, 15, 18, 22, 20, 17, 19]
}

df = pd.DataFrame(data)
df['data'] = pd.to_datetime(df['data'])
df['mes'] = df['data'].dt.month
df.head()

# 3. Gráfico - Média de PM2.5 por cidade
plt.figure(figsize=(8, 5))
sns.barplot(data=df, x="cidade", y="pm2_5", estimator=np.mean, ci=None, palette="viridis")
plt.title("Média de PM2.5 por Cidade")
plt.ylabel("PM2.5 (µg/m³)")
plt.xlabel("Cidade")
plt.tight_layout()
plt.show()

# 4. Gráfico - Evolução temporal do PM2.5
plt.figure(figsize=(10, 6))
sns.lineplot(data=df, x="data", y="pm2_5", hue="cidade", marker="o", palette="viridis")
plt.title("Evolução do PM2.5 ao Longo do Tempo por Cidade")
plt.ylabel("PM2.5 (µg/m³)")
plt.xlabel("Data")
plt.tight_layout()
plt.show()

# 5. Boxplot - Comparação de PM10 por cidade
plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x="cidade", y="pm10", palette="viridis")
plt.title("Distribuição de PM10 por Cidade")
plt.ylabel("PM10 (µg/m³)")
plt.xlabel("Cidade")
plt.tight_layout()
plt.show()

"""## 5. Resultados

- **São Paulo** apresentou os maiores valores médios de PM2.5 entre as três capitais analisadas.
- A **evolução temporal** sugere que os níveis de poluição variam com a estação do ano, sendo mais altos no verão/inverno em algumas cidades.
- O **boxplot de PM10** mostrou uma variação significativa entre cidades, com destaque para os níveis mais elevados em São Paulo e Belo Horizonte.
- Os níveis de ozônio se mantêm mais estáveis, com pequenas variações.

---

## 6. Conclusão

A análise revelou diferenças importantes na qualidade do ar entre as capitais brasileiras. São Paulo, devido ao seu grande volume de tráfego e urbanização intensa, apresentou os níveis mais altos de poluição atmosférica.

Esses dados reforçam a necessidade de políticas públicas voltadas para a **mobilidade sustentável**, **redução de emissões** e **monitoramento constante da qualidade do ar**, especialmente nas grandes cidades.

---

## 7. Referências

- Kaggle Dataset: https://www.kaggle.com/datasets/matheusfreitag/air-quality-brazil
- CETESB – Qualidade do Ar: https://cetesb.sp.gov.br/ar/
- INMET – Instituto Nacional de Meteorologia: https://www.gov.br/inmet
- IBGE – Instituto Brasileiro de Geografia e Estatística: https://www.ibge.gov.br/

---

# Observação Importante:

🧪 O que são PM2.5 e PM10?
PM significa Material Particulado – que são partículas sólidas e líquidas suspensas no ar, como poeira, fuligem, fumaça, poluição de carros e queima de lixo.

PM10: são partículas inaláveis com diâmetro de até 10 micrômetros. Elas são grandes o suficiente para entrar no nariz e garganta. Podem causar irritações respiratórias, tosses e problemas no nariz e garganta.

PM2.5: são ainda menores, com menos de 2,5 micrômetros de diâmetro. Por serem tão finas, conseguem penetrar profundamente nos pulmões e até entrar na corrente sanguínea. Estão mais associadas a problemas graves de saúde, como doenças cardíacas, respiratórias e até câncer.

🧬 Em resumo:

Quanto menor o número, mais perigosa é a partícula para a saúde.
"""

